### ISSUE TITLE
WARNING: AppData Packages not found

### ISSUE THREAD

**Issue by AlexPGroot** [AgentRev/WindowsAppsUnfukker#25]
Copy-paste this in the description: C:\Users\Alex\AppData\Local\Packages

I got this error that it was unable to find the AppData packages.
When I installed Windows it automatically named my user folder after the first 5 characters of my used email apparently (alexg). However I'd rather use a basic username and switched to local account instead. This however doesn't alter the name of the user folder that was made on installation and now I have a user folder that does not fit my username. I read if I could fix this but it could apparently break some stuff so I wasn't really that interested in doing so.

That aside, the program did work! I tried to make my Nvidia control panel work again by using the mentioned "-old renaming method". And clicking the program now results in a "The parameter is incorrect" error, instead of a permission error. So my nvidia drivers are probably just botched now, as I have the permission to open the broken program haha.

**Comment by AgentRev** [comment]
Yeah the AppData part is not really mandatory. I see a lot of people recommending the unfukker to deal with Nvidia issues on Reddit and other forums, I wish I could be of more help to you and them but I never had that particular problem myself.

**Comment by e-t-l** [comment]
Just want to add that I had the exact same issue. When I first installed Windows it took an email like "JohnDoe@domain.com" and made my username "Johnd_000". This app threw the exact same error and instructed me to file a github issue about it, because it's searching for packages in `C:\Users\JohnDoe\AppData\Local\Packages` when it _should_ be looking in `C:\Users\JohnD_000\AppData\Local\Packages`. @AgentRev You say this part is optional - that's fine, I'll take your word for it - but maybe it's worth tweaking the script just a little, then? Either to account for username inconsistencies,* or at least don't Write-Host telling people to file github issues? 

*In fact - assuming your script worked and my PC is usable again - I should be able to write a PR for it myself...
